spring:
  application:
    name: submission
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
server:
  port: 8082
core_service:
  url: ${CORE_SERVICE_URL}